image: 18.09.4

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  #DOCKER_HOST: tcp://localhost:2375
  #DOCKER_DRIVER: overlay2

build_job:
  services:
    - docker:18.09.4-dind
  stage: build
  before_script:
    - echo 'Getting, building and publishing reddit'
    - docker info
  script:
    - echo 'Building'
    - cd docker-monolith
    - docker build -t vitrez/pipeline-reddit:1.1 .
    - docker images -a

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
    - sudo docker run -d --name stage-reddit vitrez/pipeline-reddit:1.1
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
